delete loads of useless shit

diff --git a/PeepholeContest/compileall b/PeepholeContest/compileall
--- a/PeepholeContest/compileall
+++ b/PeepholeContest/compileall
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 export CLASSPATH=$(pwd)/jooslib.jar
-for d in PeepholeBenchmarks/* ; do
-    (cd $d ; make)
+
+out=/dev/null
+
+for d in $(find PeepholeBenchmarks -type d -depth 1) ; do
+    (cd $d ; if ! make ; then echo "$d failed" ; fi)
 done
